CREATE TABLE IF NOT EXISTS Item(id IDENTITY PRIMARY KEY, done BOOLEAN, text VARCHAR(255));
DELETE FROM Item;
INSERT INTO Item VALUES(1, 'item1', 20);
INSERT INTO Item VALUES(2, 'item2', 20 );
INSERT INTO Item VALUES(3, 'item2', 20);